export const CLIENT_MESSAGE = {
  REGISTER_SUCCESSFULLY: 'Đăng ký tài khoản thành công',
  EMAIL_MUST_BE_STRING: 'Email phải là dạng chuỗi',
  EMAIL_LENGTH: 'Email bắt đầu từ 5 - 160 ký tự',
  EMAIL_NOT_EMPTY: 'Email là bắt buộc',
  EMAIL_INVALID: 'Email chưa đúng định dạng',
  EMAIL_ALREADY_EXISTS: 'Email đã tồn tại',
  PASSWORD_NOT_EMPTY: 'Mật khẩu là bắt buộc',
  PASSWORD_LENGTH: 'Mật khẩu bắt đầu từ 6 - 160 ký tự',
  PASSWORD_IS_NOT_STRONG:
    'Mật khẩu phải có ít nhất 6 ký tự, 1 ký tự viết hoa, 1 ký tự viết thường, 1 ký tự số và một ký tự đặt biệt',
  CONFIRM_PASSWORD_NOT_EMPTY: 'Xác nhận mật khẩu là bắt buộc',
  CONFIRM_PASSWORD_LENGTH: 'Xác nhận mật khẩu bắt đầu từ 6 - 160 ký tự',
  CONFIRM_PASSWORD_NOT_MATCH: 'Xác nhận mật khẩu không trùng khớp',
  VERIFY_ACCOUNT_SUCCESSFULLY: 'Xác thực tài khoản thành công.',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token là bắt buộc',
  USER_NOT_FOUND: 'Không tìm thấy người dùng',
  ACCOUNT_IS_VERIFIED: 'Tài khoản đã xác thực',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token là bắt buộc',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token là bắt buộc',
  REFRESH_TOKEN_NOT_FOUND: 'Không tìm thấy token',
  RESEND_VERIFY_EMAIL_SUCCESSFULLY: 'Gửi lại email xác thực tài khoản thành công',
  EMAIL_OR_PASSWORD_INCORRECT: 'Email hoặc mật khẩu chưa chính xác',
  LOGIN_SUCCESSFULLY: 'Đăng nhập tài khoản thành công',
  LOGOUT_SUCCESSFULLY: 'Đăng xuất tài khoản thành công',
  ACCOUNT_UNVERIFIED: 'Tài khoản chưa được xác thực',
  OLD_PASSWORD_INCORRECT: 'Mật khẩu cũ không chính xác',
  CHANGE_PASSWORD_SUCCESSFULLY: 'Thay đổi mật khẩu tài khoản thành công',
  CHECK_EMAIL_TO_RESET_PASSWORD: 'Bạn vui lòng kiểm tra email để xác minh tài khoản',
  FORGOT_PASSWORD_IS_REQUIRED: 'Token quên mật khẩu là bắt buộc',
  FORGOT_PASSWORD_TOKEN_INVALID: 'Token quên mật khẩu chưa đúng định dạng',
  RESET_PASSWORD_SUCCESSFULLY: 'Đặt lại mật khẩu thành công',
  NAME_MUST_BE_STRING: 'Tên phải là dạng chuỗi',
  NAME_LENGTH: 'Tên có độ dài từ 6 đến 160 ký tự',
  DATE_OF_BIRTH_ISO8601: 'Ngày tháng năm sinh phải có định dạng là ISO8601',
  AVATAR_MUST_BE_STRING: 'Avatar phải là dạng chuỗi',
  PHONE_MUST_BE_STRING: 'Số điện thoại phải là dạng chuỗi',
  AVATAR_LENGTH: 'Avatar có độ dài từ 6 đến 1000 ký tự',
  PHONE_LENGTH: 'Phone có độ dài từ 10 đến 20 ký tự',
  ADDRESS_MUST_BE_STRING: 'Địa chỉ phải là dạng chuỗi',
  ADDRESS_MUST_BE_FROM_6_TO_160: 'Địa chỉ có độ dài từ 6 đến 1000 ký tự',
  UPDATE_ME_SUCCESSFULLY: 'Cập nhật profile thành công',
  GET_ME_SUCCESSFULLY: 'Lấy thông tin người dùng thành công',
  UPLOAD_AVATAR_SUCCESSFULLY: 'Upload avatar thành công',
  REFRESH_TOKEN_SUCCESSFULLY: 'Làm mới token thành công'
} as const

export const ADMIN_MESSAGE = {
  REGISTER_SUCCESSFULLY: 'Đăng ký tài khoản admin thành công',
  EMAIL_MUST_BE_STRING: 'Email admin phải là dạng chuỗi',
  EMAIL_LENGTH: 'Email admin bắt đầu từ 5 - 160 ký tự',
  EMAIL_NOT_EMPTY: 'Email admin là bắt buộc',
  EMAIL_INVALID: 'Email admin chưa đúng định dạng',
  EMAIL_ALREADY_EXISTS: 'Email admin đã tồn tại',
  PASSWORD_NOT_EMPTY: 'Mật khẩu admin là bắt buộc',
  PASSWORD_LENGTH: 'Mật khẩu admin bắt đầu từ 6 - 160 ký tự',
  PASSWORD_IS_NOT_STRONG:
    'Mật khẩu admin phải có ít nhất 6 ký tự, 1 ký tự viết hoa, 1 ký tự viết thường, 1 ký tự số và một ký tự đặt biệt',
  CONFIRM_PASSWORD_NOT_EMPTY: 'Xác nhận mật khẩu admin là bắt buộc',
  CONFIRM_PASSWORD_LENGTH: 'Xác nhận mật khẩu admin bắt đầu từ 6 - 160 ký tự',
  CONFIRM_PASSWORD_NOT_MATCH: 'Xác nhận mật khẩu admin không trùng khớp',
  VERIFY_ACCOUNT_SUCCESSFULLY: 'Xác thực tài khoản admin thành công.',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token admin là bắt buộc',
  USER_NOT_FOUND: 'Không tìm thấy tài khoản admin',
  ACCOUNT_IS_VERIFIED: 'Tài khoản admin đã xác thực',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token là bắt buộc',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token là bắt buộc',
  REFRESH_TOKEN_NOT_FOUND: 'Không tìm thấy token',
  RESEND_VERIFY_EMAIL_SUCCESSFULLY: 'Gửi lại email xác thực tài khoản admin thành công',
  EMAIL_OR_PASSWORD_INCORRECT: 'Email hoặc mật khẩu chưa chính xác',
  LOGIN_SUCCESSFULLY: 'Đăng nhập tài khoản thành công',
  LOGOUT_SUCCESSFULLY: 'Đăng xuất tài khoản thành công',
  ACCOUNT_UNVERIFIED: 'Tài khoản admin chưa được xác thực',
  OLD_PASSWORD_INCORRECT: 'Mật khẩu cũ admin không chính xác',
  CHANGE_PASSWORD_SUCCESSFULLY: 'Thay đổi mật khẩu admin tài khoản thành công',
  CHECK_EMAIL_TO_RESET_PASSWORD: 'Bạn vui lòng kiểm tra email để xác minh tài khoản admin',
  FORGOT_PASSWORD_IS_REQUIRED: 'Token quên mật khẩu là bắt buộc',
  FORGOT_PASSWORD_TOKEN_INVALID: 'Token quên mật khẩu chưa đúng định dạng',
  RESET_PASSWORD_SUCCESSFULLY: 'Đặt lại mật khẩu admin thành công',
  NAME_MUST_BE_STRING: 'Tên admin phải là dạng chuỗi',
  NAME_LENGTH: 'Tên admin có độ dài từ 6 đến 160 ký tự',
  DATE_OF_BIRTH_ISO8601: 'Ngày tháng năm sinh phải có định dạng là ISO8601',
  AVATAR_MUST_BE_STRING: 'Avatar admin phải là dạng chuỗi',
  PHONE_MUST_BE_STRING: 'Số điện thoại admin phải là dạng chuỗi',
  AVATAR_LENGTH: 'Avatar admin có độ dài từ 6 đến 1000 ký tự',
  PHONE_LENGTH: 'Avatar admin có độ dài từ 10 đến 20 ký tự',
  ADDRESS_MUST_BE_STRING: 'Địa chỉ admin phải là dạng chuỗi',
  ADDRESS_MUST_BE_FROM_6_TO_160: 'Địa chỉ admin có độ dài từ 6 đến 1000 ký tự',
  UPDATE_ME_SUCCESSFULLY: 'Cập nhật profile admin thành công',
  GET_ME_SUCCESSFULLY: 'Lấy thông tin tài khoản admin thành công',
  UPLOAD_AVATAR_SUCCESSFULLY: 'Upload avatar admin thành công',
  REFRESH_TOKEN_SUCCESSFULLY: 'Làm mới token admin thành công',
  SECRET_KEY_ACCEPT_ADMIN_REGITER_SITE_INVALID: 'Mã bí mật để đăng ký tài khoản admin không hợp lệ',
  SECRET_KEY_ACCEPT_ADMIN_REGITER_SITE_REQUIRED: 'Mã bí mật để đăng ký tài khoản admin là bắt buộc',
  SECRET_KEY_ACCEPT_ADMIN_REGITER_SITE_MUST_BE_STRING: 'Mã bí mật để đăng ký tài khoản phải là dạng chuỗi',
  CREATED_PRODUCT_SUCCESSFULLY: 'Thêm sản phẩm thành công',
  UPDATED_PRODUCT_SUCCESSFULLY: 'Cập nhật sản phẩm thành công',
  GET_PRODUCT_SUCCESSFULLY: 'Lấy danh sách sản phẩm thành công',
  GET_CATEGORY_PRODUCT_SUCCESSFULLY: 'Lấy danh sách danh mục sản phẩm thành công',
  GET_DETAIL_PRODUCT_SUCCESSFULLY: 'Lấy thông tin chi tiết sản phẩm thành công',
  DETELE_PRODUCT_SUCCESSFULLY: 'Xóa sản phẩm thành công',
  CATEGORY_ID_IS_REQUIRED: 'Id danh mục là bắt buộc',
  CATEGORY_ID_INVALID: 'Id danh mục chưa đúng định dạng',
  IMAGE_MUST_BE_STRING: 'Ảnh phải là dạng chuỗi',
  IMAGE_LENGTH: 'Ảnh là dạng chuỗi có độ dài từ 1 đến 1000 ký tự',
  IMAGES_MUST_BE_ARRAY_STRING: 'Gallery ảnh phải là dạng một mảng các chuỗi',
  IMAGES_IS_REQUIRED: 'Gallery ảnh là bắt buộc',
  IMAGES_ITEM_MUST_BE_ARRAY_STRING: 'Phần tử trong gallery ảnh phải là dạng chuỗi',
  SLUG_MUST_BE_STRING: 'Slug phải là dạng chuỗi',
  SLUG_LENGTH: 'Slug có độ dài từ 1 đến 500 ký tự',
  SLUG_IS_REQUIRED: 'Slug là bắt buộc',
  SLUG_INVALID: 'Slug không đúng định dạng',
  SLUG_ALREADY_EXISTS: 'Slug đã tồn tại',
  NAME_PRODUCT_MUST_BE_STRING: 'Tên sản phẩm phải là dạng chuỗi',
  NAME_CATEGORY_PRODUCT_MUST_BE_STRING: 'Tên danh mục sản phẩm phải là dạng chuỗi',
  NAME_PRODUCT_LENGTH: 'Tên sản phẩm có độ dài từ 1 đến 500 ký tự',
  NAME_CATEGORY_PRODUCT_LENGTH: 'Tên danh mục sản phẩm có độ dài từ 1 đến 500 ký tự',
  PRICE_PRODUCT_GREATER_THAN_1: 'Giá của sản phẩm phải lớn hơn 1',
  PRICE_PRODUCT_IS_REQUIRED: 'Giá của sản phẩm là bắt buộc',
  PRICE_BEFORE_DISCOUNT_MUST_BE_GREATER_THAN_PRICE: 'Giá trước khi giảm giá phải lớn hơn giá hiện tại của sản phẩm',
  PRODUCT_QUANTITY_IS_REQUIRED: 'Số lượng của sản phẩm là bắt buộc',
  PRODUCT_QUANTITY_GREATER_THAN_1: 'Số lượng của sản phẩm phải lớn hơn 1',
  PRODUCT_SOLD_GREATER_THAN_1: 'Số lượng sản phẩm bán chạy phải lớn hơn 1',
  PRODUCT_SOLD_IS_REQUIRED: 'Số lượng sản phẩm bán chạy là bắt buộc',
  PRODUCT_VIEW_IS_REQUIRED: 'Sản phẩm phổ biến là bắt buộc',
  PRODUCT_VIEW_GREATER_THAN_1: 'Sản phẩm phổ biến phải lớn hơn 1',
  PRODUCT_RATING_IS_NUMBER: 'Sao của sản phẩm phải là dạng số',
  PRODUCT_RATING_INVALID: 'Sao của sản phẩm phải lớn hơn 1 và bé hơn hoặc bằng 5',
  PRODUCT_RATING_IS_REQUIRED: 'Sao của sản phẩm là bắt buộc',
  PRODUCT_DESCRIPTION_MUST_BE_STRING: 'Mô tả sản phẩm phải là dạng chuỗi',
  PRODUCT_DESCRIPTION_LENGTH: 'Mô tả sản phẩm có độ dài từ 1 đến 5000 ký tự',
  SEO_TITLE_MUST_BE_STRING: 'Tiêu đề SEO phải là dạng chuỗi',
  SEO_TITLE_LENGTH: 'Tiêu đề SEO có độ dài từ 1 đến 1000 ký tự',
  SEO_KEYWORDS_MUST_BE_STRING: 'Keywords SEO phải là dạng chuỗi',
  SEO_KEYWORDS_LENGTH: 'Keywords SEO có độ dài từ 1 đến 2000 ký tự',
  SEO_DESCRIPTION_MUST_BE_STRING: 'Mô tả SEO phải là dạng chuỗi',
  SEO_DESCRIPTION_LENGTH: 'Mô tả SEO có độ dài từ 1 đến 5000 ký tự',
  CATEGORY_ID_MUST_BE_STRING: 'Id danh mục phải là dạng chuỗi',
  CATEGORY_PRODUCT_ID_IS_REQUIRED: 'Id danh mục của sản phẩm là bắt buộc',
  PRODUCT_ID_IS_REQUIRED: 'Id của sản phẩm là bắt buộc',
  CATEGORY_PRODUCT_ID_MUST_BE_STRING: 'Id danh mục của sản phẩm phải là dạng chuỗi',
  PRODUCT_ID_MUST_BE_STRING: 'Id của sản phẩm phải là dạng chuỗi',
  CATEGORY_PRODUCT_ID_INVALID: 'Id danh mục của sản phẩm chưa đúng định dạng',
  PRODUCT_ID_INVALID: 'Id của sản phẩm chưa đúng định dạng',
  CATEGORY_PRODUCT_NOT_FOUND: 'Không tìm thấy danh mục sản phẩm',
  PRODUCT_NOT_FOUND: 'Không tìm thấy sản phẩm',
  PRICE_PRODUCT_MUST_BE_NUMBER: 'Giá của sản phẩm phải là dạng số',
  PRICE_BEFORE_DISCOUNT_MUST_BE_NUMBER: 'Giá của sản phẩm trước khi giảm giá phải có dạng số',
  PRODUCT_QUANTITY_MUST_BE_NUMBER: 'Số lượng của sản phẩm phải là dạng số',
  PRODUCT_SOLD_MUST_BE_NUMBER: 'Số lượng sản phẩm bán chạy phải là dạng số',
  PRODUCT_VIEW_MUST_BE_NUMBER: 'Số lượng sản phẩm phổ biến phải là dạng số',
  PRODUCT_IDS_IS_REQUIRED: 'Ids của sản phẩm là bắt buộc',
  CATEGORY_PRODUCT_IDS_IS_REQUIRED: 'Ids của danh mục sản phẩm là bắt buộc',
  CATEGORY_PRODUCT_IDS_MUST_BE_ARRAY: 'Ids của danh mục sản phẩm phải là một mảng',
  PRODUCT_IDS_MUST_BE_ARRAY: 'Ids của sản phẩm phải là một mảng',
  CATEGORY_PRODUCT_IDS_ITEM_MUST_BE_ARRAY_STRING: 'Các phần tử trong mảng Id của danh mục sản phẩm phải là dạng chuỗi',
  PRODUCT_IDS_ITEM_MUST_BE_ARRAY_STRING: 'Các phần tử trong mảng Id của sản phẩm phải là dạng chuỗi',
  BUYCOUNT_IS_REQUIRED: 'Số lượng mua là bắt buộc',
  BUY_COUNT_MUST_BE_NUMBER: 'Số lượng mua phải là dạng số',
  BUYCOUNT_MUST_BE_INT_NUMBER_FROM_1: 'Số lượng mua phải là số nguyên và lớn hơn 1',
  BUYCOUNT_NOT_ALLOW_GREATER_THAN_QUANTITY_OF_PRODUCT: 'Số lượng mua không được phép lớn hơn số lượng của sản phẩm',
  TOTAL_BUYCOUNT_NOT_ALLOW_GREATER_THAN_QUANTITY_OF_PRODUCT:
    'Tổng số lượng mua trong đơn hàng không được phép lớn hơn số lượng của sản phẩm',
  ADD_TO_CART_SUCCESSFULLY: 'Thêm sản phẩm vào giỏ hàng thành công',
  PURCHASE_NOT_FOUND: 'Không tìm thấy đơn hàng',
  UPDATE_CART_SUCCESSFULLY: 'Cập nhật giỏ hàng thành công',
  STATUS_CART_IS_REQUIRED: 'Trạng thái giỏ hàng là bắt buộc',
  STATUS_CART_INVALID: 'Status cart invalid',
  GET_CART_SUCCESSFULLY: 'Lấy giỏ hàng thành công',
  PURCHASE_IDS_IS_REQUIRED: 'Mảng id của đơn hàng là bắt buộc',
  PURCHASE_IDS_MUST_BE_ARRAY: 'Puchase_ids phải là mảng chứa các id',
  PURCHASE_IDS_ITEM_MUST_BE_ARRAY_STRING: 'Các phần tử của puchase_ids phải là dạng chuỗi',
  DETELE_CART_SUCCESSFULLY: 'Xóa giỏ hàng thành công',
  BODY_CART_BUY_MUST_BE_ARRAY: 'Thanh toán giỏ hàng dữ liệu gửi lên phải ở dạng mảng',
  BODY_CART_BUY_IS_REQUIRED: 'Thanh toán giỏ hành dữ liệu gửi lên không được rỗng',
  ITEM_BODY_CART_BUY_MUST_BE_OBJECT: 'Các phần tử trong mảng dữ liệu gửi lên để thanh toán giỏ hàng phải là Object',
  BUY_PRODUCTS_SUCCESSFULLY: 'Mua hàng thành công',
  UPLOAD_IMAGE_SUCCESSFULLY: 'Upload hình ảnh thành công',
  CREATED_CATEGORY_PRODUCT_SUCCESSFULLY: 'Thêm danh mục sản phẩm thành công',
  UPDATED_CATEGORY_PRODUCT_SUCCESSFULLY: 'Cập nhật danh mục sản phẩm thành công',
  DETELE_CATEGORY_PRODUCT_SUCCESSFULLY: 'Xóa danh mục sản phẩm thành công',
  ORDER_MUST_BE_ASC_OR_DESC: 'Order phải là asc hoặc desc',
  SORT_BY_MUST_BE_CREATED_AT_VIEW_SOLD_OR_PRICE: 'Sort by phải là created_at hoặc view hoặc sold hoặc price',
  RATING_FILTER_MUST_BE_INT_NUMBER: 'Rating filter phải là số nguyên',
  RATING_FILTER_LIMIT_FROM_1_TO_5: 'Rating filter phải thuộc trong khoảng từ 1 đến 5',
  PRICE_PRODUCT_MUST_BE_INT: 'Giá của sản phẩm phải là số nguyên'
} as const
